### ISSUE TITLE
关于预先训练的wordvector.bin文件

### ISSUE THREAD

**Issue by VincentChen123** [liuhuanyong/LearningBasedSentiment#1]
你好，请问能否提供一下wordvector.bin的训练脚本，或者文件？谢谢。

**Comment by ujndong** [comment]
同求，谢谢

**Comment by limyfeel** [comment]
同求，谢谢

**Comment by Swocky** [comment]
同求

**Comment by shark803** [comment]
同求，谢谢

**Comment by GZH666** [comment]
同求，谢谢

**Comment by zgd1997** [comment]
哪位老哥能给分享一下么？

**Comment by lz222** [comment]
哪位大佬可以分享一下wordvector.bin文件啊

**Comment by lz222** [comment]
thank you ,so where can i  get this wordvector.bin file?




------------------ 原始邮件 ------------------
发件人: "Xiaowei Liu"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 中午12:16
收件人: "liuhuanyong/SentenceSentimentClassifier"<SentenceSentimentClassifier@noreply.github.com>; 
抄送: "&#x206E;&#x206E;"<794486632@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [liuhuanyong/SentenceSentimentClassifier] 关于预先训练的wordvector.bin文件 (#1)




Closed #1.

**Comment by mnwato** [comment]
Hi there
This is also my question.
I got the error which it tells there is not "wordvector.bin" 

Could you please help me?

**Comment by person11152** [comment]
同求 wordvector.bin 文件
